spring:
  datasource:
    hikari:
      maximum-pool-size: 10         # Increase from default 5
      minimum-idle: 5               # Keep some connections ready
      connection-timeout: 10000     # 10 seconds
      idle-timeout: 300000         # 5 minutes
      max-lifetime: 1200000        # 20 minutes
      validation-timeout: 5000      # 5 seconds
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
flowcase:
  apiKey: ${FLOWCASE_API_KEY}
  baseUrl: ${FLOWCASE_BASE_URL}
openai:
  apiKey: ${OPENAI_API_KEY}
  model: gpt-4
  assistantId: ${OPENAI_ASSISTANT_ID}
gemini:
    apiKey: ${GEMINI_API_KEY}
    model: gemini-1.5-pro-latest
embedding:
  enabled: false
  provider: GEMINI
  model: text-embedding-004
  dimension: 768

management:
  endpoints:
    web:
      exposure:
        include: "health" # Eksponerer /actuator/health endepunktet
  endpoint:
    health:
      probes:
        enabled: true # Aktiverer /liveness og /readiness endepunktene
      show-details: always

  health:
    # Definerer readiness-gruppen. Den er "UP" kun hvis appen OG alle avhengigheter er ok.
    group:
      readiness:
        include: "readinessState,dependencies" # Inkluderer vår egendefinerte sjekk
