version: '3.8'

services:
  postgres-local:
    image: pgvector/pgvector:pg15
    container_name: cloudberries-postgres-local
    restart: unless-stopped
    environment:
      POSTGES_DB: candidatematch
      POSTGRES_USER: candidatematch
      POSTGRES_PASSWORD: candidatematch123
    ports:
      - "5433:5432" # Bruker port 5433 for å unngå konflikt med andre instillinger
    volumes:
      - postgres_local_data:/var/lib/postgresql/data

volumes:
  postgres_local_data:
    driver: local
