/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/anthropic-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Anthropic API usage and cost statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usage statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnthropicUsageResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chatbot/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze content with AI */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AIAnalysisRequest"];
                };
            };
            responses: {
                /** @description Analysis result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AIResponseModel"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat with AI using RAG (Retrieval-Augmented Generation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RagChatRequest"];
                };
            };
            responses: {
                /** @description Chat response with sources */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RagChatResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a CV into the RAG vector store */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RagIngestRequest"];
                };
            };
            responses: {
                /** @description Ingestion result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ingested?: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest all CVs from the database into the RAG vector store */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch ingestion report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rowsProcessed?: number;
                            chunksAdded?: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List consultants (paged) */
        get: {
            parameters: {
                query?: {
                    /** @description Optional name filter (contains) */
                    name?: string;
                    /** @description Page number (0-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Page size */
                    size?: components["parameters"]["SizeParam"];
                    /** @description Sort field(s), e.g. `name,asc`. Repeat for multi-sort. */
                    sort?: components["parameters"]["SortParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged consultants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageConsultantSummaryDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/with-cv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all consultants with their CVs */
        get: {
            parameters: {
                query?: {
                    onlyActiveCv?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of consultants with CVs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsultantWithCvDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/with-cv/paged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paged consultants with their CVs */
        get: {
            parameters: {
                query?: {
                    onlyActiveCv?: boolean;
                    /** @description Page number (0-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Page size */
                    size?: components["parameters"]["SizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged consultants with CVs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageResponseConsultantWithCvDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/{userId}/cvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List CVs for a specific consultant */
        get: {
            parameters: {
                query?: {
                    onlyActiveCv?: boolean;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of consultant CVs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsultantCvDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relational search for consultants */
        post: operations["searchConsultantsRelational"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/search/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic (vector) search for consultants */
        post: operations["searchConsultantsSemantic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/search/embedding-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get information about the configured embedding provider */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Embedding provider info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmbeddingProviderInfo"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/sync/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a sync from Flowcase */
        post: {
            parameters: {
                query?: {
                    batchSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a consultant's CV (raw JSON) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CV data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings/run/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate embeddings for users missing vectors */
        post: {
            parameters: {
                query?: {
                    batchSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            processedCount?: number;
                            batchSize?: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all project requests available for matching */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of project request summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestSummaryDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests-paged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project requests with coverage information (paged) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged project requests with coverage */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedMatchesListDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{id}/top-consultants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Returns AI-enriched top consultants for a given project request
         * @description Returns previously persisted LLM evaluation when present (no LLM call). On first access, triggers a fresh LLM run and persists the result. To force a fresh run, use `POST /matches/requests/{id}/re-analyze`.
         *
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Explicit model tier for the LLM call. When provided, takes precedence over `useHighestQualityModel`. FAST = fastest/cheapest, DEFAULT = balanced, QUALITY = highest quality. If omitted, the backend picks an operation-appropriate default.
                     *      */
                    modelTier?: components["parameters"]["ModelTierParam"];
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                    /** @description Percentage weight (0–100) given to CV quality when combining with skill match. The remaining percentage is given to skill match. Frontend typically offers 20, 30, 60 or 80. If omitted, the server default (50) is used.
                     *      */
                    cvWeightPercent?: components["parameters"]["CvWeightPercentParam"];
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of AI-enriched matches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchConsultantDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{id}/re-analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-analyzes and re-ranks consultants for a project request
         * @description Forces a fresh LLM evaluation and overwrites the cached result for the given project request. Use this for an explicit "Run again" action from the UI when the user wants updated matches.
         *
         */
        post: {
            parameters: {
                query?: {
                    /** @description Explicit model tier for the LLM call. When provided, takes precedence over `useHighestQualityModel`. FAST = fastest/cheapest, DEFAULT = balanced, QUALITY = highest quality. If omitted, the backend picks an operation-appropriate default.
                     *      */
                    modelTier?: components["parameters"]["ModelTierParam"];
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                    /** @description Percentage weight (0–100) given to CV quality when combining with skill match. The remaining percentage is given to skill match. Frontend typically offers 20, 30, 60 or 80. If omitted, the server default (50) is used.
                     *      */
                    cvWeightPercent?: components["parameters"]["CvWeightPercentParam"];
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Re-analysis results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchConsultantDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{projectRequestId}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger matching computation for a specific project request */
        post: {
            parameters: {
                query?: {
                    forceRecompute?: boolean;
                    /** @description Explicit model tier for the LLM call. When provided, takes precedence over `useHighestQualityModel`. FAST = fastest/cheapest, DEFAULT = balanced, QUALITY = highest quality. If omitted, the backend picks an operation-appropriate default.
                     *      */
                    modelTier?: components["parameters"]["ModelTierParam"];
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                    /** @description Percentage weight (0–100) given to CV quality when combining with skill match. The remaining percentage is given to skill match. Frontend typically offers 20, 30, 60 or 80. If omitted, the server default (50) is used.
                     *      */
                    cvWeightPercent?: components["parameters"]["CvWeightPercentParam"];
                };
                header?: never;
                path: {
                    projectRequestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trigger status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TriggerMatchingResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/status/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status of a matching job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Match status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchStatusDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/recalculate/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalculate matches for a project request (Async) */
        post: {
            parameters: {
                query?: {
                    /** @description Explicit model tier for the LLM call. When provided, takes precedence over `useHighestQualityModel`. FAST = fastest/cheapest, DEFAULT = balanced, QUALITY = highest quality. If omitted, the backend picks an operation-appropriate default.
                     *      */
                    modelTier?: components["parameters"]["ModelTierParam"];
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                    /** @description Percentage weight (0–100) given to CV quality when combining with skill match. The remaining percentage is given to skill match. Frontend typically offers 20, 30, 60 or 80. If omitted, the server default (50) is used.
                     *      */
                    cvWeightPercent?: components["parameters"]["CvWeightPercentParam"];
                };
                header?: never;
                path: {
                    requestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recalculation accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            requestId?: number;
                            statusUrl?: string;
                            matchesUrl?: string;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/trigger-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger matching for all project requests */
        post: {
            parameters: {
                query?: {
                    forceRecompute?: boolean;
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch operation status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all project requests (paged) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged list of project requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedProjectRequestResponseDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        /** Create a new project request */
        post: {
            parameters: {
                query?: {
                    async?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateProjectRequestDto"];
                };
            };
            responses: {
                /** @description Created project request */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestDto"];
                    };
                };
                /** @description Accepted for async processing */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-requests/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload and analyze a customer project request PDF */
        post: {
            parameters: {
                query?: {
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Extracted project request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestResponseDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project request by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project request details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestResponseDto"];
                    };
                };
                /** @description Project request not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a project request
         * @description Permanently deletes the project request and its associated data (e.g. extracted requirements, AI suggestions and computed matches). Idempotent: deleting an unknown id returns 404.
         *
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project request deleted (no content) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project request not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-requests/{id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger AI analysis for an existing project request */
        post: {
            parameters: {
                query?: {
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Analysis result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestResponseDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-requests/{id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AI suggestions for a project request */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of AI suggestions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AISuggestionDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-requests/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Close a project request */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Closed project request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestResponseDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get CV score for a candidate */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    candidateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidate CV score */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CvScoreDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        /** Trigger scoring for single candidate */
        post: operations["scoreCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/{candidateId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger scoring run for single candidate */
        post: operations["runScoreForCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/{candidateId}/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalculate CV score for a single candidate */
        post: operations["recalculateScore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all candidates (summary) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandidateDTO"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/run/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger scoring for all consultants */
        post: {
            parameters: {
                query?: {
                    /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                     *      */
                    useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Scoring summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CvScoringRunResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chatbot/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI-powered consultant search (STRUCTURED / SEMANTIC / HYBRID / RAG) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatSearchRequest"];
                };
            };
            responses: {
                /** @description Chat search response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSearchResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/programming-languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated programming-language statistics across consultants */
        get: {
            parameters: {
                query?: {
                    /** @description Optional list of canonical language names (repeat to filter by multiple) */
                    languages?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Programming language statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProgrammingLanguageStat"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated role statistics across consultants */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoleStat"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List distinct skill names (optionally prefix-filtered) */
        get: {
            parameters: {
                query?: {
                    prefix?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skill names */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paged skill summary (name + consultantCount) */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    page?: number;
                    size?: number;
                    /** @description Sort, e.g. consultantCount,desc | name,asc */
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged skill summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageSkillSummaryDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate embedding for a specific user + CV */
        post: {
            parameters: {
                query: {
                    userId: string;
                    cvId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            userId?: string;
                            cvId?: string;
                            processed?: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings/run/jason": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate embedding for the seed/demo consultant ("Jason") */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            processedJason?: boolean;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flat list of top matches for a project request */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    requestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Top matches (flat list) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchItemDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{projectRequestId}/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-10 match results for a project request */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectRequestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Match top-10 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchTop10Response"];
                    };
                };
                /** @description No matches found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{projectRequestId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match results (alias of /top for backward compatibility) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    projectRequestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Match top-10 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchTop10Response"];
                    };
                };
                /** @description No matches found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matching-service health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchesHealthResponse"];
                    };
                };
                /** @description Service is DOWN */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchesHealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List skills across consultants */
        get: {
            parameters: {
                query?: {
                    /** @description Optional skill filter (repeat to filter by multiple) */
                    skill?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skill aggregates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkillInCompanyDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skill}/consultants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paged list of consultants that have the given skill */
        get: {
            parameters: {
                query?: {
                    /** @description Page number (0-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Page size */
                    size?: components["parameters"]["SizeParam"];
                    /** @description Sort field(s), e.g. `name,asc`. Repeat for multi-sort. */
                    sort?: components["parameters"]["SortParam"];
                };
                header?: never;
                path: {
                    /** @description Skill name (URL-encoded by the client) */
                    skill: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of consultants for the skill */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageConsultantSummaryDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skill}/top-consultants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top-N consultants for the given skill (no paging) */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    /** @description Skill name (URL-encoded by the client) */
                    skill: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Top consultants for the skill */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsultantSummaryDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get configured AI model tiers
         * @description Returns the resolved Anthropic model names per tier (FAST, DEFAULT, QUALITY) and a flag indicating whether QUALITY currently falls back to the DEFAULT model (i.e. when ANTHROPIC_QUALITY_MODEL is not configured). Never returns the API key.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Configured model tiers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AiModelsResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AiModelsResponse: {
            /** @example ANTHROPIC */
            provider: string;
            /** @description Resolved model name for the FAST tier */
            fastModel: string;
            /** @description Resolved model name for the DEFAULT tier */
            defaultModel: string;
            /** @description Resolved model name for the QUALITY tier (falls back to defaultModel when not configured) */
            qualityModel: string;
            /** @description True when ANTHROPIC_QUALITY_MODEL is explicitly configured (different from defaultModel) */
            qualityConfigured: boolean;
            /** @description True when QUALITY tier currently resolves to the DEFAULT model */
            qualityFallsBackToDefault: boolean;
            /** @example configuration */
            availableModelsSource: string;
        };
        AnthropicUsageResponse: {
            /** Format: int64 */
            inputTokens?: number;
            /** Format: int64 */
            outputTokens?: number;
            /** Format: int64 */
            cacheCreationTokens?: number;
            /** Format: int64 */
            cacheReadTokens?: number;
            /** Format: int64 */
            totalInputTokens?: number;
            /** Format: double */
            cacheHitRate?: number;
            /** Format: double */
            estimatedCostUsd?: number;
        };
        AIAnalysisRequest: {
            /** @description Content to analyze */
            content: string;
        };
        AIResponseModel: {
            content?: string;
            modelUsed?: string;
        };
        RagChatRequest: {
            message: string;
            /** @default 4 */
            topK: number;
            /**
             * Format: double
             * @default 0.7
             */
            similarityThreshold: number;
            filter?: string | null;
        };
        RagChatResponse: {
            answer?: string;
            sources?: components["schemas"]["SourceDocument"][];
        };
        SourceDocument: {
            id?: string | null;
            contentPreview?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        RagIngestRequest: {
            /** Format: int64 */
            candidateId: number;
            name?: string | null;
            cvText: string;
        };
        ConsultantSummaryDto: {
            userId: string;
            name: string;
            /** Format: email */
            email: string;
            bornYear: number;
            defaultCvId: string;
        };
        PageConsultantSummaryDto: {
            content?: components["schemas"]["ConsultantSummaryDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            number?: number;
            size?: number;
        };
        ConsultantWithCvDto: {
            /** Format: int64 */
            id?: number | null;
            userId: string;
            name: string;
            cvId: string;
            skills: string[];
            cvs: components["schemas"]["ConsultantCvDto"][];
        };
        ConsultantCvDto: {
            /** Format: int64 */
            id?: number | null;
            versionTag?: string | null;
            qualityScore?: number | null;
            active: boolean;
            industries: string[];
            keyQualifications?: components["schemas"]["KeyQualificationDto"][];
            education?: components["schemas"]["EducationDto"][];
            workExperience?: components["schemas"]["WorkExperienceDto"][];
            projectExperience?: components["schemas"]["ProjectExperienceDto"][];
            certifications?: components["schemas"]["CertificationDto"][];
            courses?: components["schemas"]["CourseDto"][];
            languages?: components["schemas"]["LanguageDto"][];
            skillCategories?: components["schemas"]["SkillCategoryDto"][];
            attachments?: components["schemas"]["AttachmentDto"][];
        };
        KeyQualificationDto: {
            label?: string | null;
            description?: string | null;
        };
        EducationDto: {
            degree?: string | null;
            school?: string | null;
            fromYearMonth?: string | null;
            toYearMonth?: string | null;
        };
        WorkExperienceDto: {
            employer?: string | null;
            fromYearMonth?: string | null;
            toYearMonth?: string | null;
        };
        ProjectExperienceDto: {
            customer?: string | null;
            description?: string | null;
            longDescription?: string | null;
            fromYearMonth?: string | null;
            toYearMonth?: string | null;
            roles?: components["schemas"]["ProjectRoleDto"][];
            skills?: string[];
        };
        ProjectRoleDto: {
            name?: string | null;
            description?: string | null;
        };
        CertificationDto: {
            name?: string | null;
            year?: number | null;
        };
        CourseDto: {
            name?: string | null;
            organizer?: string | null;
            year?: number | null;
        };
        LanguageDto: {
            name?: string | null;
            level?: string | null;
        };
        SkillCategoryDto: {
            name?: string | null;
            skills?: components["schemas"]["SkillInCategoryDto"][];
        };
        SkillInCategoryDto: {
            name?: string | null;
            durationYears?: number | null;
        };
        AttachmentDto: {
            fileName?: string | null;
            url?: string | null;
        };
        PageResponseConsultantWithCvDto: {
            content?: components["schemas"]["ConsultantWithCvDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            number?: number;
            size?: number;
        };
        PageConsultantWithCvDto: {
            content?: components["schemas"]["ConsultantWithCvDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            number?: number;
            size?: number;
        };
        RelationalSearchRequest: {
            name?: string | null;
            skillsAll?: string[];
            skillsAny?: string[];
            minQualityScore?: number | null;
            /** @default false */
            onlyActiveCv: boolean;
            pagination?: components["schemas"]["PaginationDto"];
        };
        SemanticSearchRequest: {
            text: string;
            /** @default GOOGLE_GEMINI */
            provider: string;
            /** @default gemini-embedding-001 */
            model: string;
            /** @default 10 */
            topK: number;
            minQualityScore?: number | null;
            /** @default false */
            onlyActiveCv: boolean;
            pagination?: components["schemas"]["PaginationDto"];
        };
        PaginationDto: {
            /** @default 0 */
            page: number;
            /** @default 10 */
            size: number;
            sort?: string[];
        };
        EmbeddingProviderInfo: {
            providerName?: string;
            modelName?: string;
            dimension?: number;
            enabled?: boolean;
        };
        ProjectRequestSummaryDto: {
            /** Format: int64 */
            id: number;
            title?: string | null;
            customerName: string;
            /** Format: date-time */
            createdAt: string;
        };
        PagedMatchesListDto: {
            content?: components["schemas"]["MatchesListItemDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            currentPage?: number;
            pageSize?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        MatchesListItemDto: {
            /** Format: int64 */
            id: number;
            title?: string | null;
            customerName?: string | null;
            /** Format: date-time */
            date?: string | null;
            /** Format: date-time */
            deadlineDate?: string | null;
            /** Format: int64 */
            hitCount: number;
            coverageStatus: components["schemas"]["CoverageStatus"];
            coverageLabel: string;
        };
        /** @enum {string} */
        CoverageStatus: "GREEN" | "YELLOW" | "RED" | "NEUTRAL";
        MatchConsultantDto: {
            userId: string;
            name: string;
            cvId: string;
            /** Format: double */
            relevanceScore: number;
            justification?: string | null;
        };
        TriggerMatchingResponse: {
            /** Format: int64 */
            projectRequestId: number;
            status: string;
            message: string;
            jobId?: string | null;
        };
        MatchStatusDto: {
            /** @description PENDING|RUNNING|COMPLETED|FAILED */
            status: string;
            /** Format: date-time */
            lastUpdated?: string | null;
            error?: string | null;
        };
        ProjectRequestResponseDto: {
            /** Format: int64 */
            id?: number;
            customerName?: string | null;
            title?: string | null;
            summary?: string | null;
            originalFilename?: string | null;
            /** Format: date-time */
            uploadedAt?: string | null;
            /** Format: date-time */
            deadlineDate?: string | null;
            status?: components["schemas"]["RequestStatus"];
            mustRequirements?: components["schemas"]["ProjectRequirementDto"][];
            shouldRequirements?: components["schemas"]["ProjectRequirementDto"][];
            aiSuggestions?: components["schemas"]["AISuggestionDto"][];
        };
        PagedProjectRequestResponseDto: {
            content?: components["schemas"]["ProjectRequestResponseDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            currentPage?: number;
            pageSize?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        ProjectRequestDto: {
            /** Format: int64 */
            id?: number | null;
            customerName?: string;
            title?: string | null;
            summary?: string | null;
            requiredSkills?: string[];
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            /** Format: date-time */
            responseDeadline?: string | null;
            status?: components["schemas"]["RequestStatus"];
            requestDescription?: string | null;
            /** Format: email */
            responsibleSalespersonEmail?: string | null;
            aiSuggestions?: components["schemas"]["AISuggestionDto"][];
        };
        /** @enum {string} */
        RequestStatus: "OPEN" | "IN_PROGRESS" | "CLOSED";
        CreateProjectRequestDto: {
            customerName: string;
            requiredSkills: string[];
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string;
            /** Format: date-time */
            responseDeadline: string;
            requestDescription?: string | null;
            /** Format: email */
            responsibleSalespersonEmail?: string | null;
            status?: components["schemas"]["RequestStatus"];
        };
        AISuggestionDto: {
            /** Format: int64 */
            id?: number | null;
            consultantName?: string;
            /** Format: double */
            matchScore?: number;
            justification?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ProjectRequirementDto: {
            name: string;
            details?: string | null;
        };
        CvScoreDto: {
            candidateId: string;
            scorePercent: number;
            summary: string;
            strengths: string[];
            potentialImprovements: string[];
        };
        CandidateDTO: {
            id: string;
            name: string;
            birthYear: number;
        };
        CvScoringRunResponse: {
            processedCount: number;
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "UP" | "DOWN" | "OUT_OF_SERVICE" | "UNKNOWN";
            details?: {
                [key: string]: string;
            };
        };
        SkillInCompanyDto: {
            name: string;
            konsulenterMedSkill: number;
            konsulenter: components["schemas"]["ConsultantSummaryDto"][];
        };
        Problem: {
            status?: number;
            error?: string;
            message?: string;
            path?: string;
        };
        ProgrammingLanguageStat: {
            language: string;
            consultantCount: number;
            /** Format: double */
            percentage: number;
            aggregatedYears: number;
        };
        RoleStat: {
            role: string;
            consultantCount: number;
            /** Format: double */
            percentage: number;
        };
        SkillSummaryDto: {
            name: string;
            consultantCount: number;
        };
        PageSkillSummaryDto: {
            content: components["schemas"]["SkillSummaryDto"][];
            number: number;
            size: number;
            totalElements: number;
            totalPages: number;
            first: boolean;
            last: boolean;
            sort?: {
                [key: string]: unknown;
            };
            pageable?: {
                [key: string]: unknown;
            };
        };
        MatchItemDto: {
            /** Format: int64 */
            requestId: number;
            /** Format: int64 */
            consultantId: number;
            name: string;
            score: number;
            reasons: string[];
            profileUrl?: string | null;
            cvQualityPercent?: number | null;
        };
        MatchTop10ConsultantDto: {
            /** Format: int64 */
            consultantId: number;
            consultantName: string;
            userId: string;
            cvId?: string | null;
            matchScore: number;
            matchExplanation?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        MatchTop10Response: {
            /** Format: int64 */
            projectRequestId: number;
            projectTitle?: string | null;
            totalMatches: number;
            matches: components["schemas"]["MatchTop10ConsultantDto"][];
            /** Format: date-time */
            lastUpdated?: string | null;
        };
        MatchesHealthResponse: {
            /** @enum {string} */
            status: "UP" | "DOWN";
            service: string;
            projectRequestsCount?: number;
            error?: string | null;
            /** Format: int64 */
            timestamp: number;
        };
        /** @enum {string} */
        ChatSearchMode: "STRUCTURED" | "SEMANTIC" | "HYBRID" | "RAG";
        ChatSearchRequest: {
            conversationId?: string | null;
            consultantId?: string | null;
            cvId?: string | null;
            text: string;
            forceMode?: components["schemas"]["ChatSearchMode"] | null;
            topK?: number | null;
        };
        ChatSearchResultItem: {
            consultantId: string;
            name: string;
            /** Format: double */
            score: number;
            highlights?: string[] | null;
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        ChatSearchSource: {
            consultantId: string;
            consultantName: string;
            chunkId: string;
            text: string;
            /** Format: double */
            score: number;
            location?: string | null;
        };
        ChatSearchResponse: {
            mode: components["schemas"]["ChatSearchMode"];
            results: components["schemas"]["ChatSearchResultItem"][];
            answer?: string | null;
            sources: components["schemas"]["ChatSearchSource"][];
            /** Format: int64 */
            latencyMs: number;
            debug?: {
                [key: string]: unknown;
            } | null;
            conversationId?: string | null;
            scoring?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description Error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Page number (0-indexed) */
        PageParam: number;
        /** @description Page size */
        SizeParam: number;
        /** @description Sort field(s), e.g. `name,asc`. Repeat for multi-sort. */
        SortParam: string[];
        /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
         *      */
        UseHighestQualityModelParam: boolean;
        /** @description Explicit model tier for the LLM call. When provided, takes precedence over `useHighestQualityModel`. FAST = fastest/cheapest, DEFAULT = balanced, QUALITY = highest quality. If omitted, the backend picks an operation-appropriate default.
         *      */
        ModelTierParam: "FAST" | "DEFAULT" | "QUALITY";
        /** @description Percentage weight (0–100) given to CV quality when combining with skill match. The remaining percentage is given to skill match. Frontend typically offers 20, 30, 60 or 80. If omitted, the server default (50) is used.
         *      */
        CvWeightPercentParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchConsultantsRelational: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationalSearchRequest"];
            };
        };
        responses: {
            /** @description Paged consultants matching filters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageConsultantWithCvDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    searchConsultantsSemantic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Paged semantically similar consultants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageConsultantWithCvDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    scoreCandidate: {
        parameters: {
            query?: {
                aiProvider?: string;
                /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                 *      */
                useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
            };
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated candidate CV score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvScoreDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    runScoreForCandidate: {
        parameters: {
            query?: {
                aiProvider?: string;
                /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                 *      */
                useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
            };
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated candidate CV score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvScoreDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    recalculateScore: {
        parameters: {
            query?: {
                aiProvider?: string;
                /** @description When true, backend requests the configured QUALITY model tier for this operation. The concrete model is configured server-side via ANTHROPIC_QUALITY_MODEL. If no quality model is configured, backend falls back to the default model.
                 *      */
                useHighestQualityModel?: components["parameters"]["UseHighestQualityModelParam"];
            };
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated candidate CV score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvScoreDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
