/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/anthropic-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Anthropic API usage and cost statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usage statistics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnthropicUsageResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chatbot/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze content with AI */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AIAnalysisRequest"];
                };
            };
            responses: {
                /** @description Analysis result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AIResponseModel"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat with AI using RAG (Retrieval-Augmented Generation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RagChatRequest"];
                };
            };
            responses: {
                /** @description Chat response with sources */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RagChatResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a CV into the RAG vector store */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RagIngestRequest"];
                };
            };
            responses: {
                /** @description Ingestion result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ingested?: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/ingest/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest all CVs from the database into the RAG vector store */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch ingestion report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rowsProcessed?: number;
                            chunksAdded?: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List consultants (paged) */
        get: {
            parameters: {
                query?: {
                    /** @description Optional name filter (contains) */
                    name?: string;
                    /** @description Page number (0-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Page size */
                    size?: components["parameters"]["SizeParam"];
                    /** @description Sort field(s), e.g. `name,asc`. Repeat for multi-sort. */
                    sort?: components["parameters"]["SortParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged consultants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageConsultantSummaryDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/with-cv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all consultants with their CVs */
        get: {
            parameters: {
                query?: {
                    onlyActiveCv?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of consultants with CVs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsultantWithCvDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/with-cv/paged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paged consultants with their CVs */
        get: {
            parameters: {
                query?: {
                    onlyActiveCv?: boolean;
                    /** @description Page number (0-indexed) */
                    page?: components["parameters"]["PageParam"];
                    /** @description Page size */
                    size?: components["parameters"]["SizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged consultants with CVs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PageResponseConsultantWithCvDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/{userId}/cvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List CVs for a specific consultant */
        get: {
            parameters: {
                query?: {
                    onlyActiveCv?: boolean;
                };
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of consultant CVs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConsultantCvDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Relational search for consultants */
        post: operations["searchConsultantsRelational"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/search/semantic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Semantic (vector) search for consultants */
        post: operations["searchConsultantsSemantic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/search/embedding-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get information about the configured embedding provider */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Embedding provider info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmbeddingProviderInfo"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultants/sync/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a sync from Flowcase */
        post: {
            parameters: {
                query?: {
                    batchSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sync summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a consultant's CV (raw JSON) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CV data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings/run/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate embeddings for users missing vectors */
        post: {
            parameters: {
                query?: {
                    batchSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Operation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            processedCount?: number;
                            batchSize?: number;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all project requests available for matching */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of project request summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestSummaryDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests-paged": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project requests with coverage information (paged) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paged project requests with coverage */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PagedMatchesListDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{id}/top-consultants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns AI-enriched top consultants for a given project request */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of AI-enriched matches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchConsultantDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{id}/re-analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-analyzes and re-ranks consultants for a project request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Re-analysis results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchConsultantDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/requests/{projectRequestId}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger matching computation for a specific project request */
        post: {
            parameters: {
                query?: {
                    forceRecompute?: boolean;
                };
                header?: never;
                path: {
                    projectRequestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trigger status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TriggerMatchingResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/status/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the status of a matching job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Match status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MatchStatusDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/recalculate/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalculate matches for a project request (Async) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    requestId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recalculation accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            requestId?: number;
                            statusUrl?: string;
                            matchesUrl?: string;
                        };
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/trigger-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger matching for all project requests */
        post: {
            parameters: {
                query?: {
                    forceRecompute?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch operation status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-requests/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload and analyze a customer project request PDF */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Extracted project request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectRequestResponseDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get CV score for a candidate */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    candidateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidate CV score */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CvScoreDto"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        /** Trigger scoring for single candidate (alias for /run) */
        post: operations["runScoreForCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/{candidateId}/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalculate CV score for a candidate */
        post: operations["recalculateScoreForCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all candidates (summary) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Candidates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CandidateDTO"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cv-score/run/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger scoring for all consultants */
        post: {
            parameters: {
                query?: {
                    /** @description Optional AI provider override (e.g. ANTHROPIC) */
                    aiProvider?: components["parameters"]["AiProviderParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Scoring summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CvScoringRunResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List skills across consultants */
        get: {
            parameters: {
                query?: {
                    /** @description Optional skill filter (repeat to filter by multiple) */
                    skill?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Skill aggregates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SkillInCompanyDto"][];
                    };
                };
                default: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnthropicUsageResponse: {
            /** Format: int64 */
            inputTokens?: number;
            /** Format: int64 */
            outputTokens?: number;
            /** Format: int64 */
            cacheCreationTokens?: number;
            /** Format: int64 */
            cacheReadTokens?: number;
            /** Format: int64 */
            totalInputTokens?: number;
            /** Format: double */
            cacheHitRate?: number;
            /** Format: double */
            estimatedCostUsd?: number;
        };
        AIAnalysisRequest: {
            /** @description Content to analyze */
            content: string;
        };
        AIResponseModel: {
            content?: string;
            modelUsed?: string;
        };
        RagChatRequest: {
            message: string;
            /** @default 4 */
            topK: number;
            /**
             * Format: double
             * @default 0.7
             */
            similarityThreshold: number;
            filter?: string | null;
        };
        RagChatResponse: {
            answer?: string;
            sources?: components["schemas"]["SourceDocument"][];
        };
        SourceDocument: {
            id?: string | null;
            contentPreview?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        RagIngestRequest: {
            /** Format: int64 */
            candidateId: number;
            name?: string | null;
            cvText: string;
        };
        ConsultantSummaryDto: {
            userId: string;
            name: string;
            /** Format: email */
            email: string;
            bornYear: number;
            defaultCvId: string;
        };
        PageConsultantSummaryDto: {
            content?: components["schemas"]["ConsultantSummaryDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            number?: number;
            size?: number;
        };
        ConsultantWithCvDto: {
            /** Format: int64 */
            id?: number | null;
            userId: string;
            name: string;
            cvId: string;
            skills: string[];
            cvs: components["schemas"]["ConsultantCvDto"][];
        };
        ConsultantCvDto: {
            /** Format: int64 */
            id?: number | null;
            versionTag?: string | null;
            qualityScore?: number | null;
            active: boolean;
            industries: string[];
            keyQualifications?: components["schemas"]["KeyQualificationDto"][];
            education?: components["schemas"]["EducationDto"][];
            workExperience?: components["schemas"]["WorkExperienceDto"][];
            projectExperience?: components["schemas"]["ProjectExperienceDto"][];
            certifications?: components["schemas"]["CertificationDto"][];
            courses?: components["schemas"]["CourseDto"][];
            languages?: components["schemas"]["LanguageDto"][];
            skillCategories?: components["schemas"]["SkillCategoryDto"][];
            attachments?: components["schemas"]["AttachmentDto"][];
        };
        KeyQualificationDto: {
            label?: string | null;
            description?: string | null;
        };
        EducationDto: {
            degree?: string | null;
            school?: string | null;
            fromYearMonth?: string | null;
            toYearMonth?: string | null;
        };
        WorkExperienceDto: {
            employer?: string | null;
            fromYearMonth?: string | null;
            toYearMonth?: string | null;
        };
        ProjectExperienceDto: {
            customer?: string | null;
            description?: string | null;
            longDescription?: string | null;
            fromYearMonth?: string | null;
            toYearMonth?: string | null;
            roles?: components["schemas"]["ProjectRoleDto"][];
            skills?: string[];
        };
        ProjectRoleDto: {
            name?: string | null;
            description?: string | null;
        };
        CertificationDto: {
            name?: string | null;
            year?: number | null;
        };
        CourseDto: {
            name?: string | null;
            organizer?: string | null;
            year?: number | null;
        };
        LanguageDto: {
            name?: string | null;
            level?: string | null;
        };
        SkillCategoryDto: {
            name?: string | null;
            skills?: components["schemas"]["SkillInCategoryDto"][];
        };
        SkillInCategoryDto: {
            name?: string | null;
            durationYears?: number | null;
        };
        AttachmentDto: {
            fileName?: string | null;
            url?: string | null;
        };
        PageResponseConsultantWithCvDto: {
            content?: components["schemas"]["ConsultantWithCvDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            number?: number;
            size?: number;
        };
        PageConsultantWithCvDto: {
            content?: components["schemas"]["ConsultantWithCvDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            number?: number;
            size?: number;
        };
        RelationalSearchRequest: {
            name?: string | null;
            skillsAll?: string[];
            skillsAny?: string[];
            minQualityScore?: number | null;
            /** @default false */
            onlyActiveCv: boolean;
            pagination?: components["schemas"]["PaginationDto"];
        };
        SemanticSearchRequest: {
            text: string;
            /** @default GOOGLE_GEMINI */
            provider: string;
            /** @default gemini-embedding-001 */
            model: string;
            /** @default 10 */
            topK: number;
            minQualityScore?: number | null;
            /** @default false */
            onlyActiveCv: boolean;
            pagination?: components["schemas"]["PaginationDto"];
        };
        PaginationDto: {
            /** @default 0 */
            page: number;
            /** @default 10 */
            size: number;
            sort?: string[];
        };
        EmbeddingProviderInfo: {
            providerName?: string;
            modelName?: string;
            dimension?: number;
            enabled?: boolean;
        };
        ProjectRequestSummaryDto: {
            /** Format: int64 */
            id: number;
            title?: string | null;
            customerName: string;
            /** Format: date-time */
            createdAt: string;
        };
        PagedMatchesListDto: {
            content?: components["schemas"]["MatchesListItemDto"][];
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
            currentPage?: number;
            pageSize?: number;
            hasNext?: boolean;
            hasPrevious?: boolean;
        };
        MatchesListItemDto: {
            /** Format: int64 */
            id: number;
            title?: string | null;
            customerName?: string | null;
            /** Format: date-time */
            date?: string | null;
            /** Format: date-time */
            deadlineDate?: string | null;
            /** Format: int64 */
            hitCount: number;
            coverageStatus: components["schemas"]["CoverageStatus"];
            coverageLabel: string;
        };
        /** @enum {string} */
        CoverageStatus: "GREEN" | "YELLOW" | "RED" | "NEUTRAL";
        MatchConsultantDto: {
            userId: string;
            name: string;
            cvId: string;
            /** Format: double */
            relevanceScore: number;
            justification?: string | null;
        };
        TriggerMatchingResponse: {
            /** Format: int64 */
            projectRequestId: number;
            status: string;
            message: string;
            jobId?: string | null;
        };
        MatchStatusDto: {
            /** @description PENDING|RUNNING|COMPLETED|FAILED */
            status: string;
            /** Format: date-time */
            lastUpdated?: string | null;
            error?: string | null;
        };
        ProjectRequestResponseDto: {
            /** Format: int64 */
            id?: number;
            customerName?: string;
            title?: string;
            summary?: string;
            originalFilename?: string;
            mustRequirements?: components["schemas"]["ProjectRequirementDto"][];
            shouldRequirements?: components["schemas"]["ProjectRequirementDto"][];
        };
        ProjectRequirementDto: {
            name: string;
            details?: string;
        };
        CvScoreDto: {
            candidateId: string;
            scorePercent: number;
            summary: string;
            strengths: string[];
            potentialImprovements: string[];
        };
        CandidateDTO: {
            id: string;
            name: string;
            birthYear: number;
        };
        CvScoringRunResponse: {
            processedCount: number;
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "UP" | "DOWN" | "OUT_OF_SERVICE" | "UNKNOWN";
            details?: {
                [key: string]: string;
            };
        };
        SkillInCompanyDto: {
            name: string;
            konsulenterMedSkill: number;
            konsulenter: components["schemas"]["ConsultantSummaryDto"][];
        };
        Problem: {
            status?: number;
            error?: string;
            message?: string;
            path?: string;
        };
    };
    responses: {
        /** @description Error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Page number (0-indexed) */
        PageParam: number;
        /** @description Page size */
        SizeParam: number;
        /** @description Sort field(s), e.g. `name,asc`. Repeat for multi-sort. */
        SortParam: string[];
        /** @description Optional AI provider override (e.g. ANTHROPIC) */
        AiProviderParam: "ANTHROPIC" | "OPENAI" | "GOOGLE_GEMINI";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchConsultantsRelational: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationalSearchRequest"];
            };
        };
        responses: {
            /** @description Paged consultants matching filters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageConsultantWithCvDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    searchConsultantsSemantic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Paged semantically similar consultants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageConsultantWithCvDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    runScoreForCandidate: {
        parameters: {
            query?: {
                /** @description Optional AI provider override (e.g. ANTHROPIC) */
                aiProvider?: components["parameters"]["AiProviderParam"];
            };
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated candidate CV score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvScoreDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    recalculateScoreForCandidate: {
        parameters: {
            query?: {
                /** @description Optional AI provider override (e.g. ANTHROPIC) */
                aiProvider?: components["parameters"]["AiProviderParam"];
            };
            header?: never;
            path: {
                candidateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recalculated candidate CV score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvScoreDto"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
